apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-db
  namespace: demo-supabase
spec:
  template:
    spec:
      volumes:
      - name: initdb-migrations
        emptyDir: {}
      - name: initdb-init-scripts
        emptyDir: {}
      initContainers:
      - name: copy-init-scripts
        image: busybox
        command:
        - sh
        - -c
        - |
          mkdir -p /docker-entrypoint-initdb.d/migrations
          mkdir -p /docker-entrypoint-initdb.d/init-scripts
          cp /custom-init-scripts/97-_supabase.sql /docker-entrypoint-initdb.d/migrations/97-_supabase.sql
          cp /custom-init-scripts/99-logs.sql /docker-entrypoint-initdb.d/migrations/99-logs.sql
          cp /custom-init-scripts/99-realtime.sql /docker-entrypoint-initdb.d/migrations/99-realtime.sql
          cp /custom-init-scripts/99-pooler.sql /docker-entrypoint-initdb.d/migrations/99-pooler.sql
          cp /custom-init-scripts/98-webhooks.sql /docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
          cp /custom-init-scripts/99-roles.sql /docker-entrypoint-initdb.d/init-scripts/99-roles.sql
          cp /custom-init-scripts/99-jwt.sql /docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
        volumeMounts:
        - name: custom-init-scripts
          mountPath: /custom-init-scripts
        - name: initdb-scripts-data
          mountPath: /docker-entrypoint-initdb.d