apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-db
  namespace: demo-supabase
spec:
  template:
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: supabase-db
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
        - docker-entrypoint.sh
        - postgres