{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "storage") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
    - port: {{ .Values.storage.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "storage") | nindent 4 }}
{{- end }}