{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "db") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "db") | nindent 4 }}
{{- end }}