{{- if .Values.studio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "studio") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studio.service.type }}
  ports:
    - port: {{ .Values.studio.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "studio") | nindent 4 }}
{{- end }}