{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "auth") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "auth") | nindent 4 }}
{{- end }}