{{- if and .Values.nginxTemplates.enabled .Values.nginxTemplates.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nginxTemplates.serviceAccount.name | default (printf "%s-nginx-templates" (include "supabase.fullname" .)) }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
{{- end }}
