{{- if .Values.supavisor.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.fullname" . }}-supavisor-config
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  pooler.exs: |
    {:ok, _} = Application.ensure_all_started(:supavisor)

    {:ok, version} =
      case Supavisor.Repo.query!("select version()") do
        %{rows: [[ver]]} -> Supavisor.Helpers.parse_pg_version(ver)
        _ -> {:ok, "15.0"}
      end

    params = %{
      "external_id" => "{{ .Values.supavisor.tenantId }}",
      "db_host" => "{{ include "supabase.fullname" . }}-supabase-db",
      "db_port" => {{ .Values.db.service.port }},
      "db_database" => "{{ .Values.secret.db.database }}",
      "require_user" => false,
      "auth_query" => "SELECT * FROM pgbouncer.get_auth($1)",
      "default_max_clients" => {{ .Values.supavisor.maxClientConn }},
      "default_pool_size" => {{ .Values.supavisor.defaultPoolSize }},
      "default_parameter_status" => %{"server_version" => version},
      "users" => [
        # Manager user
        %{
          "db_user" => "pgbouncer",
          "db_password" => "{{ .Values.secret.db.password }}",
          "mode_type" => "{{ .Values.supavisor.poolMode }}",
          "pool_size" => {{ .Values.supavisor.defaultPoolSize }},
          "is_manager" => true
        },
        # Regular postgres user with tenant ID format
        %{
          "db_user" => "{{ .Values.secret.db.username }}",
          "db_user_alias" => "{{ .Values.secret.db.username }}.{{ .Values.supavisor.tenantId }}",
          "db_password" => "{{ .Values.secret.db.password }}",
          "mode_type" => "{{ .Values.supavisor.poolMode }}",
          "pool_size" => {{ .Values.supavisor.defaultPoolSize }},
          "is_manager" => false
        }
      ]
    }

    if !Supavisor.Tenants.get_tenant_by_external_id(params["external_id"]) do
      {:ok, _} = Supavisor.Tenants.create_tenant(params)
    end
{{- end }}
