{{- if .Values.supavisor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "supavisor") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.supavisor.service.type }}
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: 6543
      targetPort: pooler
      protocol: TCP
      name: pooler
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "supavisor") | nindent 4 }}
{{- end }}
