{{- if .Values.kong.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "kong") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - port: {{ .Values.kong.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "kong") | nindent 4 }}
{{- end }}