{{- if .Values.vector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.service.fullname" (list . "vector") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vector.service.type }}
  ports:
    - port: {{ .Values.vector.service.port }}
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.service.selectorLabels" (list . "vector") | nindent 4 }}
{{- end }}