{{- if .Values.vector.enabled -}}
{{- if .Values.vector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.service.serviceAccountName" (list . "vector") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.vector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "supabase.service.fullname" (list . "vector") }}-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supabase.service.fullname" (list . "vector") }}-view
subjects:
  - kind: ServiceAccount
    name: {{ include "supabase.service.serviceAccountName" (list . "vector") }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "supabase.service.fullname" (list . "vector") }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
