{{- if .Values.imgproxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.service.fullname" (list . "imgproxy") }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.imgproxy.autoscaling.enabled }}
  replicas: {{ .Values.imgproxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.service.selectorLabels" (list . "imgproxy") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.imgproxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.service.selectorLabels" (list . "imgproxy") | nindent 8 }}
    spec:
      {{- with .Values.imgproxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.service.serviceAccountName" (list . "imgproxy") }}
      securityContext:
        {{- toYaml .Values.imgproxy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.service.name" (list . "imgproxy") }}
          securityContext:
            {{- toYaml .Values.imgproxy.securityContext | nindent 12 }}
          image: "{{ .Values.imgproxy.image.repository }}:{{ .Values.imgproxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imgproxy.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.imgproxy.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.imgproxy.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.imgproxy.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            {{- with .Values.imgproxy.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /var/lib/storage
              name: imgproxy-volume
          {{- with .Values.imgproxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- with .Values.imgproxy.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: imgproxy-volume
          persistentVolumeClaim:
            claimName: {{ include "supabase.service.fullname" (list . "storage") }}-pvc
      {{- with .Values.imgproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imgproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imgproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}